version: '2'
services:
    jhipstersampleapplicationsql-app:
        image: jhipstersampleapplicationsql
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationsql-mysql:3306/jhipstersampleapplicationsql?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    jhipstersampleapplicationsql-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplicationsql-mysql
